### ISSUE TITLE
Firefly Server behind Traefik BasicAuth

### ISSUE THREAD

**Issue by mgorfer** [dreautall/waterfly-iii#123]
I am using Traefik in my smart home, and my Firefly Server, which is accessible via firefly.mydomain.com, is protected by the BasicAuth of this service.

https://doc.traefik.io/traefik/middlewares/http/basicauth/

When trying to log in with watefly-iii, I am getting a 
```
Unexpected HTTP status code
Host: https://firefly.mydomain.com
Status Code: 401
```

Is there a method, to enter my login data somewhere in waterfly-iii, or do I need to change something in the security of my domain? How should the normal security of my firefly server be, to be compatible with waterfly-iii?

I am really new in all of this self-hosting business, so I am sorry if this is some very basic user problem I am presenting here.

**Comment by mgorfer** [comment]
I added the BasicAuth, because I thought double the security cannot hurt. But you are right, I could just switch it off. waterfly-iii works flawlessly in that condition.

I tried your idea. It is working in my browser, to directly reach the login page of firefly. It is not working in waterfly-iii though. I am getting the same error as before.

I would be glad if you could add an option to access the firefly server through BasicAuth, but I will just turn off the basicAuth for now.
So that Feature Request has very low priority from my side :)

**Comment by mgorfer** [comment]
Thank you for the update!
I will try to implement your suggestion on my side.

**Comment by ahatdude** [comment]
> Thank you for the update! I will try to implement your suggestion on my side.

I apologise for revisiting this old issue, but @mgorfer would you be kind enough to explain to me how you added this exception to the firefly container? I'm on unraid and I'm having trouble knowing what I should be adding as a label or what I should be changing in the config to allow Waterfly to access my server with no issue.

Thanks :-)
