### ISSUE TITLE
Login in firelfy Version 6.1.9 not possible

### ISSUE THREAD

**Issue by mtettke123** [dreautall/waterfly-iii#404]
getting "unexpected HTTP status code" when trying to login. Status code is 401.

Login via webinterface works.

**Comment by mtettke123** [comment]
I'm using the "command line auth key" (freely translated from the german version). I think, this is the correct one?

**Comment by mtettke123** [comment]
Wow, that was the problem. Still dont understand why it appeared after upgrading firefly... 
So, solved. Sorry!

**Comment by nasmi3** [comment]
After updating the connection broke for me too. Then, I deleted and recreated the token and it works again.
